### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by r20222** [RayanSp/server-side-rendering-Vinimini#8]
mooie wiki.
Alleen het ontwerpen mist nog, misschien kan je hier nog een paar schetsen inzetten.

Tip: Je kan je code voorbeelden ook als echte code erin zetten ipv screenshots. Je gebruikt dan deze tekens met daarachter de bijv JS van javascript of HTML van html ``` . 

```HTML
<h1>hoi</h1>
```

**Comment by RayanSp** [comment]
- Ik heb mijn schetsen er nu ingezet.
  - De tip van de code erin zetten zal ik meenemen en zeker gebruiken.
