### ISSUE TITLE
Wiki review

### ISSUE THREAD

**Issue by Maaike0904** [RayanSp/server-side-rendering-Vinimini#9]
Tops:
* Bij bouwen goed je if else uitgelegd.
* Goed je issues verwerkt (gesloten)

Tips:
* Op je wiki homepage linkjes nog goed laten linken naar de pagina’s
* Bij de Analysefase zou je misschien nog iets kunnen zeggen over de debriefing die we tijd terug hebben gemaakt.
* Ontwerpfase mist nog informatie
* Je zou bij de testfase bij toegankelijkheid nog kunnen aangeven wat er precies is met de kleuren. Dat de blauw-groene kleur bijvoorbeeld niet genoeg contrast heeft met de witte achtergrond waardoor lighthouse dit als niet accessible ziet en het percentage daarom blijft steken op 95%.

**Comment by RayanSp** [comment]
- De linkjes werken nu wel
  - Ik heb wat meer getypt over de debriefing
  - Ik heb nu een volledige ontwerpfase 
   - Ik heb wat meer getypt over de toegankelijkheid
